### ISSUE TITLE
About test CARS196

### ISSUE THREAD

**Issue by AnshanTJU** [PkuRainBow/Hard-Aware-Deeply-Cascaded-Embedding_release#2]
Hi,
I have a problem when test CARS196. Would pls. help me?
Traceback (most recent call last):
  File "hdc_test.py", line 126, in <module>
    main(sys.argv[1:])
  File "hdc_test.py", line 55, in main
    data_cnt, feature_dim, top_cnt)
  File "/export/anshan/hardmining/Hard-Aware-Deeply-Cascaded-Embedding_release-master/src_code/test_cars196.py", line 70, in eval_HDC
    get_recall(dists, query_label_vector, data_label_vector, top_cnt)
  File "/export/anshan/hardmining/Hard-Aware-Deeply-Cascaded-Embedding_release-master/src_code/test_cars196.py", line 11, in get_recall
    labels_sorted = data_label_vector[np.argsort(dists[i, :])].flatten()
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by PkuRainBow** [comment]
@AnshanTJU  I guess this issue is related to the your lmdb of  features. In my platform, it is ok. You could just debug the code step by step. I mean that you could watch the whether the dists variable is valid and stores a matrix of float distances.

**Comment by PkuRainBow** [comment]
@AnshanTJU  I strongly recommend you debug the code in your platform step by step to find the problem, which would be more efficient.  If you still can not solve it, pls provide a snap of your variable **dists** when debugging.

**Comment by AnshanTJU** [comment]
Hi, Yuan,
It seems an error for Numpy. I have reinstalled Numpy but it also occured. The dists variable is about 300 MB so I can't transmit it to you. Do you have any advices?

**Comment by Usernamezhx** [comment]
I have meet this quesiton too.my dist look like this : 
![_20171214153723](https://user-images.githubusercontent.com/14010625/33980645-bc0d517c-e0e4-11e7-9a2b-adb364eaa6d4.jpg)
